### ISSUE TITLE
Primary-Secondary

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpegem#13]
Any opposition to adding back the primary to results where we are using primary-secondary formulation? (This has messed with me > 3 times already, haha). It doesn't change anything in the derivs or adjoint, so it is a simple change. 

It is odd to me to get two different results depending on the formulation you use (ie. Problem_e or Problem_b same thing right now with _h and _j),so I would prefer to see them give the same results.

**Comment by rowanc1** [comment]
Is this changed in the HJ formulation pull request?

**Comment by lheagy** [comment]
Not yet. I also want to remove the extra commented code before I update the
request. I will give seogi a chance to check it out first though

**Comment by lheagy** [comment]
Adding back the primary is going to take a bit of thought, so I will not include it in this pull request

**Comment by lheagy** [comment]
New source definitions will allow for this. We still need to implement supporting source terms
SrcFDEM_PrimaryProblem ?

**Comment by lheagy** [comment]
ability to do p-s now there with new source classes (and is tested with the mag dipole source using the Problem_b formulation!)

**Comment by rowanc1** [comment]
This issue was moved to simpeg/simpeg#137
