### ISSUE TITLE
Testing against analytics

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpegem#19]
We should test both e, b fields against analytic (right now, we only look at b) 
- [ ] add B fields from dipole in a whole-space
- [ ] E fields from a dipole in a whole space
- [ ] J
- [ ] H
- [ ] do a cross-check test here to (e from b, b from e, ... ) 
- [ ] casing analytic

**Comment by lheagy** [comment]
and should be applied to h-j formulation as well

**Comment by rowanc1** [comment]
This issue was moved to simpeg/simpeg#143
