### ISSUE TITLE
Full Anisotropy

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpegem#22]
At the moment, MeSigmaIDeriv, MfRhoDeriv, MfRhoDeriv will not take fully anisotropic media - this actually needs to be taken care of inside of getFaceInnerProductDeriv and getEdgeInnerProductDeriv within simpeg, but I am creating the issue here too so it is documented that the fully anisotropic inversion won't be working yet

**Comment by rowanc1** [comment]
This issue was moved to simpeg/simpeg#146
