### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpegem#29]
We attach FDEM to everything (it is a bit of overkill). What do you guys think of: 

Sources: 
EM.FDEM.SrcFDEM.SrcFDEM_MagDipole --> EM.FDEM.Src.MagDipole 

Receivers:
EM.FDEM.RxFDEM --> EM.FDEM.Rx 

Problem:
EM.FDEM.ProblemFDEM_b --> EM.FDEM.Problem_b 

Fields:
EM.FDEM.FieldsFDEM_b --> EM.FDEM.Fields_b

@rowanc1 @sgkang @grosenkj

**Comment by sgkang** [comment]
Sounds reasonable. What happen when we use same module on time domain? For example, we may share some sources in TDEM.

Cheers,
Seogi

**Comment by lheagy** [comment]
There is still some work to be done to figure it out for the time domain, but I think we can use the same structure / namespace, ie for a TDEM source: EM.TDEM.Src.MagDipole instead of what it is currently. (We may be able to have the TDEM and FDEM sources inherit from the same base class?)

**Comment by lheagy** [comment]
or do we want:

EM.FDEM.Survey.Rx
EM.FDEM.Survey.Src.MagDipole

(similar for TDEM)
?

**Comment by sgkang** [comment]
I prefer the past one.



2015-07-17 8:15 GMT+09:00 Lindsey <notifications@github.com>:

**Comment by rowanc1** [comment]
Yeah, I like them under something other than survey. Like your first setup.

**Comment by lheagy** [comment]
will do!

**Comment by lheagy** [comment]
Another one for you all:

There are a lot of derivatives to keep track of, but it boils down to taking derivatives wrt the model, m, and the field we compute, u. My suggestion is that any time we create a thing, ie. getA, we should specify which derivative we are taking: ie. getADeriv_m. This becomes important when taking derivatives of fields in the fields object as aliased fields have (potentially) derivatives wrt both m and u. 

So basically any time "Deriv" is used, it should be followed by either "_u" or "_m". What do you guys think?

**Comment by rowanc1** [comment]
Makes sense as we are talking about the function c(m,u). Would clear a lot
up for me in the flow code.

**Comment by rowanc1** [comment]
This issue was moved to simpeg/simpeg#153
